name: Daily Run

on:
  workflow_dispatch:
  schedule:
    # RUN DAILY AT 09:00 UTC
    - cron: '0 9 * * *'

jobs:

  Scraper:
    uses: ./.github/actions/scraper.yaml

  Comparer:
    needs: Scraper
    uses: ./.github/actions/comparer.yaml

  Inserter:
    needs: Scraper
    uses: ./.github/actions/inserter.yaml

  PP:
    needs: Inserter
    uses: ./.github/actions/pp.yaml
