name: Daily Run

on:
  workflow_dispatch:
  schedule:
    # RUN DAILY AT 09:00 UTC
    - cron: '0 8 * * *'

jobs:

  Scraper:
    uses: ./.github/workflows/scraper.yaml

  Comparer:
    needs: Scraper
    uses: ./.github/workflows/comparer.yaml

  Inserter:
    needs: Scraper
    uses: ./.github/workflows/inserter.yaml

  PP:
    needs: Inserter
    uses: ./.github/workflows/pp.yaml
