name: Scrape Colruyt Products

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:

  Scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: 'echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > key.json'
      - run: export GOOGLE_APPLICATION_CREDENTIALS=key.json
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: cd scraper && go get ./...
      - run: go build -o scrape scraper/main.go
      - run: ./scrape
