name: Scraper, Comparer, Inserter

on:
  workflow_dispatch:
  schedule:
    # RUN DAILY AT 06:00 UTC
    - cron: '0 6 * * *'

jobs:
  
  Scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3
      - run: 'echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > key.json'
      - run: 'echo "GOOGLE_APPLICATION_CREDENTIALS=\"key.json\"" >> .env'
      - run: go build -o scraper-exec ./scraper
      - run: ./scraper-exec
  
  Comparer:
    runs-on: ubuntu-latest
    needs: Scraper

    steps:
      - uses: actions/checkout@v3
      - run: 'echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > key.json'
      - run: 'echo "GOOGLE_APPLICATION_CREDENTIALS=\"key.json\"" >> .env'
      - run: go build -o comparer-exec ./comparer
      - run: ./comparer-exec
  
  Inserter:
    runs-on: ubuntu-latest
    needs: Scraper

    steps:
      - uses: actions/checkout@v3
      - run: 'echo "DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}" >> .env'
      - run: go build -o inserter-exec ./inserter
      - run: ./inserter-exec
