name: Scrape Colruyt Products

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  
  Scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: 'echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > key.json'
      - run: 'echo "GOOGLE_APPLICATION_CREDENTIALS=\"key.json\"" >> .env'
      - run: 'echo "" >> .env'
      - run: 'echo "SCRAPER_API_KEY=\"${{ secrets.SCRAPER_API_KEY }}\"" >> .env'
      - run: go get ./...
      - run: go build ./scraper
      - run: ./scraper
